### ISSUE TITLE
Can I use it on Linux

### ISSUE THREAD

**Issue by x93008** [thismachinechills/screenshot#6]
I want use it on linux

**Comment by alexdelorenzo** [comment]
Hi @x93008, thanks for taking the time to open an issue. Right now, this library targets macOS in an effort to take screenshots in a more programmable manner. 

Ironically, I found Linux to have better options when trying to take screenshots programmatically. Since you've expressed interest, I can adapt this library to run on Linux, especially since I've migrated back to Linux on all of my machines. 

Pretty sure this can be adapted to use `scrot` to take screenshots, and `wmctl` to get window information from the window manager on Linux. I'm unsure if those utilities will work on Wayland, however.
